<?php

/**
 * @file
 * Primary module hooks for search_api_mark_outdated module.
 *
 * @DCG
 * This file is no longer required in Drupal 8.
 * @see https://www.drupal.org/node/2217931
 */

use Drupal\Core\Entity\ContentEntityInterface;
use Drupal\Core\Entity\EntityInterface;
use Drupal\search_api\IndexInterface;
use Drupal\search_api\Plugin\search_api\datasource\ContentEntity;

/**
 * Implements hook_entity_update().
 */
function search_api_mark_outdated_entity_update(EntityInterface $entity) {
  // Check if the entity is a content entity.
  if (!($entity instanceof ContentEntityInterface) || $entity->search_api_skip_tracking) {
    return;
  }

  $indexes = ContentEntity::getIndexesForEntity($entity);
  if (!$indexes) {
    return;
  }

  \Drupal::service('search_api_mark_outdated.manager')
    ->entityUpdate($indexes, $entity);
}

/**
 * Implements function hook_search_api_items_indexed().
 */
function search_api_mark_outdated_search_api_items_indexed(IndexInterface $index, array $item_ids) {
  \Drupal::service('search_api_mark_outdated.manager')
    ->itemsIndexed($index, $item_ids);
}
